const SENSORS = {
  TIME: 'Hora GPS',
  POSITION: 'Posición',
  MAGNETICCOMPASS: 'Brúj. magnética',
  SG: 'Grav. específica',
  IS_VALID: 'Pos. GPS válida',
  GPSCOMPASS: 'Brúj. GPS',
  GPSSNR: 'Señal/Ruido GPS',
  GPSSATS: 'Nº sat. GPS',
  LAT: 'Latitud',
  LONG: 'Longitud',
  LAT_H: 'Orientación latitud',
  LONG_H: 'Orientacion longitud',
  DO: 'Oxígeno disuelto',
  TDS: 'Total sólidos disueltos',
  S: 'Salinidad',
  EC: 'EC',
  PH: 'PH',
  ORP: 'Pot. óxido red.',
  PRESS: 'Sensor presión',
  DEPTHTOTAL: 'Prof. total',
  DEPTHTOSURFACE: 'Dist. a superficie',
  DEPTHTOBOTTOM: 'Prof. al fondo',
  WATERTMP1: 'Tª ecosonda',
  WATERTMP2: 'Temperatura',
  WATERTMP3: 'Tª sensor presión',
};

export default SENSORS;
